apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
stringData:
  # Do not use plain text passwords in production!
  admin-password: "SuperSecretPassword123"
  standby-password: "StandbySecretPassword123"
